---
title: "DREAM CPTAC: survival analysis"
author: "MI YANG"
date: "`r doc_date()`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for HTML documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::html_document
---

```{r include=FALSE, cache=FALSE}
#  https://github.com/bioFAM/MOFA/tree/reticulate
#  library(devtools); devtools::load_all("/Users/miyang/Documents/RWTH_Aachen/PACKAGES/MOFA-reticulate/MOFAtools/")
#  git clone https://github.com/bioFAM/MOFA
#  library(devtools); devtools::load_all("/Users/miyang/Documents/RWTH_Aachen/PACKAGES/BIOFAM/biofam-biofamtools/BioFAMtools/")

path <- "~/Documents/RWTH_Aachen"
library(devtools); devtools::load_all(paste0(path,"/PACKAGES/MOFA-reticulate/MOFAtools/"))
library(MOFAtools) 
library("survminer")  #  http://www.sthda.com/english/rpkgs/survminer/
require("survival")
library(corrplot)
source(paste0(path,"/FUNCTIONS/general_functions.R" ))
source(paste0(path,"/FUNCTIONS/survival_analysis_functions.R" ))
source(paste0(path,"/FUNCTIONS/PLOT.R" ))
result_folder <- paste0(path,"/DREAM_CPTAC/PROT_PREDICTION/DATA_RESULT_STORAGE/MOFA/05_version_common/")

survival_analysis_continuous = function(CAT, CLINICS){ #  CLINICS=CLINICS_breast
  library(reshape)
  library(survminer)
  status = CLINICS$EVENT
  stime = CLINICS$DAYS_TO_LAST_FOLLOWUP
  var_01 = CLINICS$AGE
  var_02 = CLINICS$GENDER
  var_03 = CLINICS$`Basal.like`
  var_04 = CLINICS$LuminalB
  var_05 = CLINICS$`HER2.enriched`
  var_06 = CLINICS$`Normal.like`
  var_07 = CLINICS$T2
  var_08 = CLINICS$T3
  var_09 = CLINICS$T4
  var_10 = CLINICS$TX
  
  RESULTS = list()
  n.dead.cases = table(status)['1']
  n.dead.cases[ is.na(n.dead.cases) ] = 1

  if( n.dead.cases > 3 ) {
    for (predictor in colnames(CAT)){  ##  predictor="HSH2D"
      X = CAT[  , predictor  ]
      X <- as.numeric(X)  
      
      # mysurfit2 = coxph(Surv(stime, status) ~ X)  #  summary(mysurfit)
      if( length(unique(var_02)) > 1 ) # gender
        mysurfit2 = coxph(Surv(stime, status) ~ var_01+var_02+var_03+var_04+var_05+var_06+var_07+var_08+var_09+var_10+X)
      # var_01+var_02+var_03+var_04+var_05+var_06+var_07+var_08+var_09+var_10
      if( length(unique(var_02)) == 1 )# gender  
        mysurfit2 = coxph(Surv(stime, status) ~ age+X)   #  summary(mysurfit2)
      X_pval = summary(mysurfit2)$coefficients['X', 'Pr(>|z|)']  #  Cox p-value tests if strata is significantly associated with survival.
      X_coef = unname(coef(mysurfit2)['X'])
      RESULTS[[predictor]] = c(predictor= predictor, X_pval = X_pval, 'X_coef' = X_coef ) 
      # mysurvdiff = survdiff(Surv(stime, status) ~ X) # 
      X_pval[ is.na(X_pval) ] = 10
      #  summary( mysurfit2 ) ; basehaz(mysurfit2) predictSurvProb
      #  put here for 3 levels discretization
    }
    RESULTS = lapply(RESULTS, function(x) data.frame(t(data.frame(x, stringsAsFactors = F)), stringsAsFactors = F) )
    mRESULTS = melt(RESULTS, id.vars = colnames(RESULTS[[1]]) )
    names(mRESULTS)[ names(mRESULTS) == 'L1' ] = 'predictor'
    mRESULTS$X_adjpval = p.adjust(mRESULTS$X_pval, method = 'fdr')
  }
  mRESULTS <- mRESULTS[ ,c(1,2,5,3)]
#   fit <- coxph(Surv(stime, status) ~ age+gender+X)
#   plot(survfit(fit)) 
  return(mRESULTS)
}

survival_KM_plot <- function(CLINICS,title,size=25) {
  library(survminer)
  status = CLINICS$EVENT
  stime = CLINICS$DAYS_TO_LAST_FOLLOWUP
  var_01 = CLINICS$AGE
  var_02 = CLINICS$GENDER
  var_03 = CLINICS$`Basal.like`
  var_04 = CLINICS$LuminalB
  var_05 = CLINICS$`HER2.enriched`
  var_06 = CLINICS$`Normal.like`
  var_07 = CLINICS$T2
  var_08 = CLINICS$T3
  var_09 = CLINICS$T4
  var_10 = CLINICS$TX

  fit <- survfit( coxph ( Surv(DAYS_TO_LAST_FOLLOWUP, EVENT) ~ strata(Biomarker)+AGE+GENDER, data = CLINICS) )
  # fit <- survfit( Surv(DAYS_TO_LAST_FOLLOWUP, EVENT) ~ Biomarker, data = data )
  # http://www.sthda.com/english/wiki/survminer-r-package-survival-data-analysis-and-visualization
  size <- size
  ggsurvplot(
    fit,                  # survfit object with calculated statistics.
    size=2,               # line size
    censor.size=8,        # censor point size
    legend.labs = c("low", "high"),
    data = CLINICS,          # data used to fit survival curves.
    risk.table = F,       # show risk table.
    pval = F,             # show p-value of log-rank test.
    conf.int = F,         # show confidence intervals for 
    # point estimates of survival curves.
    # xlim = c(0,5000),   # present narrower X axis, but not affect
    # survival estimates.
    xlab = "Time in days",     # customize X axis label.
    break.time.by = 3000,      # break X axis in time intervals by 500.
    ggtheme = theme_light(),   # customize plot and risk table with a theme.
    risk.table.y.text.col = T, # colour risk table text annotations.
    risk.table.y.text = F,     # show bars instead of names in text annotations
    title = title,
    # in legend of risk table
    font.title=size, font.subtitle=size, font.caption=size, font.x=size, font.y=size, font.tickslab=size, font.legend=size 
  )  
}


```


## choose FDR < 5%
```{r rmarkdown, eval=FALSE}

#################################### load factor ####################################
all_view <- "predicted_protein"                 ; view_name <- "Protein"
all_view <- "mRNA"                              ; view_name <- "mRNA"
all_view <- "predicted_protein_mRNA"            ; view_name <- "Protein + mRNA"

factor_name <- paste0("breast_",all_view,"_FactorDrop0.01")
f <- list.files(paste0(result_folder,factor_name), recursive=FALSE, pattern="run", include.dirs = TRUE)
path2 <- paste0(result_folder,factor_name)

#################################### Select Models ####################################
MOFAlist <- list()
for(file in 1:length(f)) {  ## file=1 ; 
  load(paste0(path2,"/",f[file],"/MOFAobject.Rdata")) ; MOFAlist[[file]] <- MOFAobject 
}

compareModels(MOFAlist)
selected_MOFAobject <- selectModel(MOFAlist)
Factor_matrix <- selected_MOFAobject@Expectations$Z[ ,-1] ; colnames(Factor_matrix) <- paste0("Factor_",1:length(colnames(Factor_matrix)) ) 
# compareFactors(MOFAlist)

## save selected model
save(selected_MOFAobject,file=paste0(result_folder,factor_name,"/selected_model/selected_MOFAobject.Rdata") ) 
write.csv(Factor_matrix, paste0(result_folder,factor_name,"/selected_model/Factor_matrix"))

CLINICS <- read.csv(paste0(path,"/TCGA/DATA/CLINICS_breast"), row.names=1)
common <- intersect(rownames(CLINICS),rownames(Factor_matrix))
CLINICS <- CLINICS[common, ] ; Factor_matrix <- Factor_matrix[common, ]
Factor_matrix <- data.frame(Factor_matrix)

# Factor_matrix_bin <- binarize_by_column(Factor_matrix, 0.5, binary = T)
table <- survival_analysis_continuous (CAT=Factor_matrix, CLINICS=CLINICS ) ; table$X_pval <- as.numeric(table$X_pval) ; table
top_hits <- which(table$X_adjpval < 0.05)
df <- cbind(Factor_matrix_bin, CLINICS)

png(file=paste0(result_folder,factor_name,"/selected_model/Data_description.png") , width = 400 , height = 400 )
plotTilesData(selected_MOFAobject)
dev.off()
pdf(file=paste0(result_folder,factor_name,"/selected_model/VarianceExplained.pdf"), width = 7 , height = 7, onefile = F )
plotVarianceExplained(selected_MOFAobject)
dev.off()

############################################ plot survival ###########################################

for(i in 1:length(top_hits)) {
  pdf(file=paste0(result_folder,factor_name,"/selected_model/KM_plot_",paste0("Factor ",top_hits[i]),".pdf"), width = 9 , height = 9, onefile = F )
  df_2 <- cbind(df[ ,top_hits[i]], df) ; colnames(df_2)[1] <- "Biomarker" ; 
  print( survival_KM_plot(CLINICS=df_2,  title=paste0(view_name,", Factor ",top_hits[i],", p=",formatC(table$X_pval[top_hits[i]], format = "e", digits = 1) ), size = 32  )  )
  dev.off()
}

########################################### Factor weights ###########################################

view="mRNA"
view="predicted_protein"

for(i in 1:length(top_hits)) {
  pdf(file=paste0(result_folder,factor_name,"/selected_model/TopWeights_",view,"_Factor_",top_hits[i],".pdf"), width = 8 , height = 8, onefile = F )
  print( plotTopWeights(selected_MOFAobject,view=view, factor=top_hits[i], nfeatures = 20) ) 
  dev.off()
}

# W_1 <- MOFAobject@Expectations$W$predicted_protein[ ,-1] ; rownames(W_1) <- paste0("prot_",rownames(W_1))
# W_2 <- MOFAobject@Expectations$W$mRNA[ ,-1] ; rownames(W_2) <- paste0("mRNA_",rownames(W_2))
# cor.test(W_1[ ,8], W_2[ ,5])

####################################### enrichment analysis ##########################################

# Load reactome annotations, binary matrix with feature sets in rows and feautres in columns
# data("reactomeGS") ; Hugo <- ENS_to_Hugo(colnames(reactomeGS)) ; reactomeGS <- reactomeGS[ ,names(Hugo)] ; colnames(reactomeGS) <- Hugo
# save(reactomeGS, file="/Users/miyang/Documents/RWTH_Aachen/GENERAL_DATA/REACTOME/reactomeGS.Rdata")
load(paste0(path,"/GENERAL_DATA/REACTOME/reactomeGS.Rdata"))

# perform enrichment analysis https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4543476/
fsea.out <- FeatureSetEnrichmentAnalysis(selected_MOFAobject,view, reactomeGS, alpha = 0.05) 
Barplot_FeatureSetEnrichmentAnalysis(fsea.out, alpha=0.05)
q_value <- data.matrix(fsea.out$pval.adj)

for(i in 1:length(top_hits)) {
  pdf(file=paste0(result_folder,factor_name,"/selected_model/FSEA_",view,"_Factor_",top_hits[i],".pdf"), width = 12 , height = 6, onefile = F )
  lineplot <- LinePlot_FeatureSetEnrichmentAnalysis(fsea.out,top_hits[i], threshold=0.05, max.pathways=20)
  print(lineplot)
  dev.off()
}


################################### Explaining relevant Factors #######################################

VIEW <- c("mRNA")
VIEW <- c("predicted_protein")
VIEW <- c("mRNA","predicted_protein")

for(i in 1:length(top_hits)) {
  pubmed_result_Factor <- c()
  for(view in VIEW) {
    MOFAweights <- getWeights(selected_MOFAobject, views=view, factors=top_hits[i], as.data.frame = T) ; MOFAweights <- MOFAweights[ order(-abs(MOFAweights$value)) , ]
    pubmed_result <- find_pubmed_association("breast", MOFAweights$feature[1:10] , constant_term="cancer")
    pubmed_result <- paste0(colnames(pubmed_result)," (", pubmed_result,")")
    pubmed_result_Factor <- rbind(pubmed_result_Factor, pubmed_result)
  }
  rownames(pubmed_result_Factor) <- VIEW ; colnames(pubmed_result_Factor) <- paste0("rank_",1:10)
  write.csv(pubmed_result_Factor, paste0(result_folder,factor_name,"/selected_model/pubmed_result_Factor_",top_hits[i]) )
}


```


