---
title: "DREAM CPTAC: Challenge Result Description"
author: "MI YANG"
date: "`r doc_date()`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for HTML documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::html_document
---
```{r include=FALSE, cache=FALSE}
library(openxlsx)
path <- "~/Documents/RWTH_Aachen"
source(paste0(path,"/FUNCTIONS/general_functions.R"))
source(paste0(path,"/FUNCTIONS/PLOT.R"))
source(paste0(path,"/DREAM_CPTAC/PROT_PREDICTION/PROT_ANALYSIS_functions.R"))
```


## DOWNLOAD APRTICIPANTS' PREDICTION FILES

```{r include=FALSE, cache=FALSE}

library(synapseClient) 
synapseLogin()

#  sc2: proteomics subchallenge
#  sc3: phosphoproteomics subchallenge

sub_challenge_name <- "sc2_breast"

prediction_file <- paste0(path,"/DREAM_CPTAC/CHALLENGE_RESULT/finalround/PREDICTIONS/")
outdir <- paste0(path,"/DREAM_CPTAC/CHALLENGE_RESULT/finalround/PREDICTIONS/",sub_challenge_name)

result_table <- read.xlsx(paste0(prediction_file,sub_challenge_name,".xlsx"), 1 ) 
result_table <- result_table[ -grep("Mi YANG", result_table$team), ] ###### Don't do this for sc3

result_table$PREDICTION_FILE <- as.character(result_table$PREDICTION_FILE)
result_table <- result_table[ order(-result_table$corr) , ]  ########### Use corrNew for sc3 breast

mat <- list()
for(i in 1:length(result_table$PREDICTION_FILE)) {
  entity <- synGet(result_table$PREDICTION_FILE[i])
  getFileLocation(entity)
  unzip(getFileLocation(entity),exdir=outdir)
  x <- read.delim(paste0(outdir,"/predictions.tsv"), row.names = 1)
  mat[[i]] <- x
}

common_genes = Reduce(intersect, lapply(mat, row.names))
mat = lapply(mat, function(x) { x[row.names(x) %in% common_genes,] })
names(mat) <- result_table$team
save(mat, file=paste0(outdir,"/mat_list.Rdata"))

```



## SUB CHALLENGE 2: Random permutation scoring

```{r include=FALSE, cache=FALSE}


# sub_challenge_name <- "sc2_breast"
# truth <- read.delim(paste0(path,"/DREAM_CPTAC/DATA_prospective/SC2/prospective_breast_proteome_sort_common_gene_10005.txt"), row.names=1)
# protein <- read.csv(paste0(path,"/DREAM_CPTAC/PROT_PREDICTION/DATA/breast_protein.txt"), sep="")

sub_challenge_name <- "sc2_ovarian"
truth <- read.delim(paste0(path,"/DREAM_CPTAC/DATA_prospective/SC2/prospective_ova_proteome_sort_common_gene_7061.txt"), row.names=1)
protein <- read.csv(paste0(path,"/DREAM_CPTAC/PROT_PREDICTION/DATA/ovarian_protein.txt"), sep="")

outdir <- paste0(path,"/DREAM_CPTAC/CHALLENGE_RESULT/finalround/PREDICTIONS/",sub_challenge_name)
load(paste0(outdir, "/mat_list.Rdata")) ; 

correlation_by_row_FINAL_ROUND_sc2 <- function(pred, truth, protein) {
  prediction <- pred
  test_prot  <- truth
  common_protein <- protein
  
  prediction <- prediction[common_protein, colnames(test_prot)]
  test_prot <- test_prot[common_protein, colnames(test_prot)]
  
  mat1 <- as.matrix(prediction)
  mat2 <- as.matrix(test_prot) 
  
  corr_vec <- c()
  for(i in 1:length(mat1[ ,1]) ) {  #  length(mat1[ ,1])
    c <- rbind(mat1[i, ], mat2[i, ]) ; c <- c[ ,complete.cases(t(c))]
    temp <- cor.test(mat1[ i, ], mat2[ i , ])
    pcorr <- temp$estimate # pearson correlation
    if (is.na(pcorr)) {pcorr<-0}
    corr_vec <- c(corr_vec , pcorr)
  }
  names(corr_vec) <- rownames(mat1)
  return(corr_vec)
}

NRMSE_by_row_FINAL_ROUND_sc2 <- function(pred, truth, protein)  {
  suppressPackageStartupMessages(library(hydroGOF))
  prediction <- pred
  test_prot  <- truth
  common_protein <- protein
  
  prediction <- prediction[common_protein, colnames(test_prot)]
  test_prot <- test_prot[common_protein, colnames(test_prot)]
  
  mat1 <- as.matrix(prediction)
  mat2 <- as.matrix(test_prot) 
  
  nrmse_vec <- c()
  for(i in 1:length(mat1[ ,1]) ) {
    temp <- hydroGOF::rmse(mat1[i,], mat2[i,],na.rm=T)
    nrmse_vec <- c(nrmse_vec , temp/(max(mat2[i,],na.rm=T)-min(mat2[i,],na.rm=T)))
  }
  names(nrmse_vec) <- rownames(mat1)
  return(nrmse_vec)
}


corr_store <- c()
NRMSE_store <- c()
for(iteration in 1:100) {
  for(i in 1:length(mat)) {   #   i=26
    mat_1 <- mat[[i]]
    mat_2 <- mat_1[ , sample(ncol(mat_1)) ]
    colnames(mat_2) <- colnames(mat_1)
    
    corr_vect <- correlation_by_row_FINAL_ROUND_sc2 (pred=mat_2, truth=truth, protein=protein$IDs)
    corr_store <- cbind(corr_store, mean(corr_vect) )
    
    NRMSE_vect <- NRMSE_by_row_FINAL_ROUND_sc2 (pred=mat_2, truth=truth, protein=protein$IDs)
    NRMSE_store <- cbind(NRMSE_store, mean(NRMSE_vect) )
    
  }
}
prediction_score_Protein_MEAN_random <- t(rbind(corr_store, NRMSE_store))
colnames(prediction_score_Protein_MEAN_random) <- c("corr","NRMSE")
write.csv(prediction_score_Protein_MEAN_random, paste0(outdir,"/prediction_score_Protein_MEAN_random"))


```


## SUB CHALLENGE 3: Random permutation scoring

```{r include=FALSE, cache=FALSE}

sub_challenge_name <- "sc3_breast"
truth <- read.delim(paste0(path,"/DREAM_CPTAC/DATA_prospective/SC3/truth_breast.txt"), row.names=1)
protein <- read.csv(paste0(path,"/DREAM_CPTAC/PROT_PREDICTION/DATA/breast_phosphosites.txt"), sep="")

sub_challenge_name <- "sc3_ovarian"
truth <- read.delim(paste0(path,"/DREAM_CPTAC/DATA_prospective/SC3/truth_ovarian.txt"), row.names=1)
protein <- read.csv(paste0(path,"/DREAM_CPTAC/PROT_PREDICTION/DATA/ovarian_phosphosites.txt"), sep="")

outdir <- paste0(path,"/DREAM_CPTAC/CHALLENGE_RESULT/finalround/PREDICTIONS/",sub_challenge_name)
load(paste0(outdir, "/mat_list.Rdata")) ; 

correlation_by_row_FINAL_ROUND_sc3 <- function(pred, truth, protein) {
  prediction <- pred
  test_prot  <- truth
  common_protein <- protein
  prediction <- prediction[common_protein, colnames(test_prot)]
  test_prot <- test_prot[common_protein, colnames(test_prot)]
  mat1 <- as.matrix(prediction)
  mat2 <- as.matrix(test_prot) 
  
  corr_vec <- c()
  for(i in 1:length(mat1[ ,1]) ) {
    c <- rbind(mat1[i, ], mat2[i, ]) ; c <- c[ ,complete.cases(t(c))]
    if( (class(c)=="matrix") && (length(c[1, ])>3) )  {
      temp <- cor.test(mat1[ i, ], mat2[ i , ])
      pcorr <- temp$estimate # pearson correlation
      if (is.na(pcorr)) {pcorr<-0}
      corr_vec <- c(corr_vec , pcorr)
    }
  }
  return(corr_vec)
}

NRMSE_by_row_FINAL_ROUND_sc3 <- function(pred, truth, protein)  {
  suppressPackageStartupMessages(library(hydroGOF))
  prediction <- pred
  test_prot  <- truth
  common_protein <- protein
  
  prediction <- prediction[common_protein, colnames(test_prot)]
  test_prot <- test_prot[common_protein, colnames(test_prot)]
  
  mat1 <- as.matrix(prediction)
  mat2 <- as.matrix(test_prot) 
  
  nrmse_vec <- c()
  for(i in 1:length(mat1[ ,1]) ) {
    temp <- hydroGOF::rmse(mat1[i,], mat2[i,],na.rm=T)
    nrmse_vec <- c(nrmse_vec , temp/(max(mat2[i,],na.rm=T)-min(mat2[i,],na.rm=T)))
  }
  names(nrmse_vec) <- rownames(mat1)
  return(nrmse_vec)
}


corr_store <- c()
NRMSE_store <- c()
for(iteration in 1:100) {
  for(i in 1:length(mat)) {   #   i=1
    mat_1 <- mat[[i]]
    mat_2 <- mat_1[ , sample(ncol(mat_1)) ]
    colnames(mat_2) <- colnames(mat_1)
    
    corr_vect <- correlation_by_row_FINAL_ROUND_sc3 (pred=mat_2, truth=truth, protein=protein$Phosphosites)
    corr_store <- cbind(corr_store, mean(corr_vect) )
    
    NRMSE_vect <- NRMSE_by_row_FINAL_ROUND_sc3 (pred=mat_2, truth=truth, protein=protein$Phosphosites)
    NRMSE_store <- cbind(NRMSE_store, mean(NRMSE_vect,na.rm=T) )
    
  }
}
prediction_score_Protein_MEAN_random <- t(rbind(corr_store, NRMSE_store))
colnames(prediction_score_Protein_MEAN_random) <- c("corr","NRMSE")
write.csv(prediction_score_Protein_MEAN_random, paste0(outdir,"/prediction_score_Protein_MEAN_random"))

```


## CHALLENGE RESULT
```{r, echo=FALSE, fig.height = 6, fig.width=8}

path1 <- paste0(path,"/DREAM_CPTAC/CHALLENGE_RESULT/finalround/")
result_folder <- paste0(path,"/DREAM_CPTAC/PLOT/finalround/")

prepare_data <- function(file,path) {
  sc <- read.xlsx(paste0(path,file,".xlsx"), 1)
  sc <- sc[complete.cases(sc), c("team","rmse","corr")]
  sc_corr <- aggregate(corr ~ team, data = sc, max)
  sc_nrmse <- sc[ sc$corr %in%  sc_corr[ ,2], ]
  sc_nrmse <- sc_nrmse[ !duplicated(sc_nrmse$team) , ]
  sc <- sc_nrmse[order(sc_nrmse$team), ]
  colnames(sc)[2] <- "NRMSE"
  df <- sc ; rownames(df) <- df$team ; df <- df[ ,-1] ; colnames(df) <- c("a","b") ;   df$a <- -log10(df$a)
  return(df)
}

scatter_plot <- function(df,title,x_lab,y_lab,baseline_corr,baseline_NRMSE=0,text_size=35,title_size=3,color,top_team) {
  df <- df[order(-df$b), ]
  top_hits  <- df[ 1:top_team , ] ; label_top_hits <- rownames(top_hits)
#  top_hits  <- df[ with(df, b <= 50 & b >= 30) , ] ; top_hits <- top_hits[complete.cases(top_hits), ] ; label_top_hits <- rownames(top_hits)
  rest  <- df[ which(rownames(df) %not in% label_top_hits) , ] ; label_rest <- rownames(rest)
  g <- ggplot(df, aes(a, b, color=b)) + 
    geom_point(shape = 16, size = 8, show.legend = FALSE, alpha = 0.8,color=color) + labs(x = x_lab, y=y_lab ) + ggtitle(title) + 
    theme(legend.position="none",axis.text=element_text(size= text_size) , axis.title= element_text(size=text_size), plot.title = element_text(size =rel(title_size), hjust = 0.5 ),
    panel.background = element_rect(fill='white'),panel.grid.major = element_line(colour = "grey90") ) + 
    scale_x_continuous( breaks=c(-5,-2,0,2 ), limits=c(-5, 2))  + 
    scale_y_continuous( breaks=c(-0.1,0,0.2,0.4,0.6), limits=c(-0.1,0.6))  + 
    # geom_text_repel(data=top_hits ,aes(label=label_top_hits), size=8, force = 5, min.segment.length = 0.1, color="black") + 
    scale_color_gradient(low = "#990000", high = "#990000" )
  g  + geom_hline(yintercept=baseline_corr,size=1, color="black",linetype="dashed") + geom_vline(xintercept = baseline_NRMSE,size=1, color="black",linetype="dashed") + coord_flip() #  + geom_text(aes(x=-6, label="Baseline", y=baseline-0.025), size=12,color="black")
}

library(cowplot)
pdf(file=paste0(result_folder,"Final_round_result_ALL.pdf"), width = 40, height = 6 ,  compress=TRUE, onefile = F)
par(mfrow=c(1,4))

metrics_name <- substitute(paste("Pearson's ",italic('R')))

df <- prepare_data(file="sc2_breast",path1)
fig1 <- scatter_plot(df,title="Protein (breast)",x_lab = "-log10(NRMSE)", y_lab = metrics_name ,baseline_corr=0.33,baseline_NRMSE=0.18,color="#CC79A7",top_team=4)
df <- prepare_data(file="sc2_ovarian",path1)
fig2 <- scatter_plot(df,title="Protein (ovarian)",x_lab = "-log10(NRMSE)", y_lab = metrics_name ,baseline_corr=0.46,baseline_NRMSE=-0.27,color="#009E73",top_team=4)
df <- prepare_data(file="sc3_breast",path1)
fig3 <- scatter_plot(df,title="Phosphoprotein (breast)",x_lab = "-log10(NRMSE)", y_lab = metrics_name ,baseline_corr=0.39,color="#D55E00",top_team=2)
df <- prepare_data(file="sc3_ovarian",path1)
fig4 <- scatter_plot(df,title="Phosphoprotein (ovarian)",x_lab = "-log10(NRMSE)", y_lab = metrics_name ,baseline_corr=0.22,baseline_NRMSE=0.67,color="#0072B2",top_team=2)
plot_grid(fig1,fig2, fig3,fig4, nrow = 1, ncol = 4 , scale = 0.99 )  # 
dev.off()


#  title="Protein (breast)" ; x_lab = "-log10(NRMSE)" ; y_lab = "Pearson's r" ; baseline=0.33 ; color="#CC79A7" ; top_team=4 ; text_size=35  ;  title_size=3

density_plot <- function(df,title,x_lab,y_lab,text_size=37,title_size=3,color ) {
  outdir <- paste0(path,"/DREAM_CPTAC/CHALLENGE_RESULT/finalround/PREDICTIONS/",sub_challenge_name)
  df <- prepare_data(file=sub_challenge_name,path1) ; df$c <- "Participants"
  data <- read.csv(paste0(outdir, "/prediction_score_Protein_MEAN_random"), row.names = 1)
  
  data$NRMSE <- -log10(data$NRMSE) ; if(length(which(data$corr==0)) > 0) { data <- data[ -which(data$corr==0), ] }
  colnames(data) <- c("b","a") ; data <- data[ , c("a","b")] ;  data$c <- "random"; rownames(data) <- paste0(rep("random",length(rownames(data)) ),1:length(rownames(data)))
  df <- rbind(df, data)
  colnames(df)[3] <- "Group"
  ggplot(df) + geom_density(aes(x = b, fill = Group), alpha = 0.5) + labs(x = x_lab ) + ggtitle(title) + scale_fill_manual(values = c(color,"grey") ) + theme(legend.position="bottom",axis.text=element_text(size= text_size, hjust = 0.5) , axis.title= element_text(size=text_size), plot.title = element_text(size =rel(title_size), hjust = 0.5 ),legend.title=element_text(size=text_size), legend.text=element_text(size=text_size),panel.background = element_rect(fill='white'),panel.grid.major = element_line(colour = "grey90") )
}


library(cowplot)
pdf(file=paste0(result_folder,"Final_round_result_ALL_density.pdf"), width = 40, height = 10 ,  compress=TRUE, onefile = F)
par(mfrow=c(1,4))

metrics_name <- substitute(paste("Pearson's ",italic('R')))

sub_challenge_name <- "sc2_breast"
fig1 <- density_plot(df,title="Protein (breast)",x_lab = metrics_name , color="#CC79A7")
sub_challenge_name <- "sc2_ovarian"
fig2 <- density_plot(df,title="Protein (ovarian)",x_lab = metrics_name , color="#009E73")
sub_challenge_name <- "sc3_breast"
fig3 <- density_plot(df,title="Phosphoprotein (breast)",x_lab = metrics_name , color="#D55E00") 
sub_challenge_name <- "sc3_ovarian"
fig4 <- density_plot(df,title="Phosphoprotein (ovarian)",x_lab = metrics_name , color="#0072B2") 
plot_grid(fig1,fig2, fig3,fig4, nrow = 1, ncol = 4 , scale = 0.99 )  # 
dev.off()



```


## POST challenge SURVEY

```{r include=FALSE, cache=FALSE}

## SC2

path1 <- paste0(path,"/DREAM_CPTAC/CHALLENGE_RESULT/finalround/")
sc2_ovarian <- read.xlsx(paste0(path1,"sc2_ovarian.xlsx"), 1 )
sc2_breast <- read.xlsx(paste0(path1,"sc2_breast.xlsx"), 1 )
common_team <- intersect(sc2_breast$team, sc2_ovarian$team)

survey <- read.xlsx(paste0(path,"/DREAM_CPTAC/CHALLENGE_RESULT/SURVEY/post_challenge_survey.xlsx"), 1)
survey <- survey[-1,10:81]
common_team <- intersect(common_team, survey$`What.is.your.team.name?`)

survey <- survey[which(survey$`What.is.your.team.name?` %in% common_team), ]
sc2_breast <- sc2_breast[which(sc2_breast$team %in% common_team) , ]
sc2_ovarian <- sc2_ovarian[which(sc2_ovarian$team %in% common_team) , ]

sc2_breast <- aggregate(corr ~ team, data = sc2_breast, max)
sc2_ovarian <- aggregate(corr ~ team, data = sc2_ovarian, max)
sc2_overall <- sc2_breast ; sc2_overall$corr <- (sc2_breast$corr + sc2_ovarian$corr)/2

sc2_overall <- sc2_overall[order(sc2_overall[ ,1]), ]
survey <- survey[order(survey[ ,1]), ]

survey <- cbind(sc2_overall$corr, survey) ; rownames(survey) <- survey$`What.is.your.team.name?` ; survey <- survey[ ,-2]
survey <- survey[ ,c(1,23:72)] 
survey <- survey[ order(-survey$`sc2_overall$corr`) , ]    #  storedata(survey, "/Users/miyang/Documents/RWTH_Aachen/DREAM_CPTAC/CHALLENGE_RESULT/SURVEY")
colnames(survey)


```


